CREATE TABLE public.kits (
    id_kits smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.kits_id_kits_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    num_serie text DEFAULT 'NULL'::text,
    nombre text DEFAULT 'NULL'::text,
    marca text DEFAULT 'NULL'::text,
    ubicacion text DEFAULT 'NULL'::text,
    observaciones text DEFAULT 'NULL'::text,
    link text DEFAULT 'NULL'::text,
    caja text DEFAULT 'NULL'::text NOT NULL,
    cantidad_kits smallint,
    contenido text DEFAULT 'NULL'::text NOT NULL,
    cantidad integer NOT NULL
    CONSTRAINT kits_pkey PRIMARY KEY (id_kits)
);

CREATE TABLE public.manuales (
    id_manual smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.manuales_id_manual_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    codigo character varying,
    manual character varying,
    topico character varying,
    cantidad integer,
    ubicacion text NOT NULL,
    referencia character varying,
    presentacion character varying,
    idioma character varying,
    observaciones character varying,
    CONSTRAINT manuales_pkey PRIMARY KEY (id_manual)
);

CREATE TABLE public.materiales (
    id_material integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.materiales_id_material_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    num_serie text DEFAULT 'NA'::text,
    nombre text NOT NULL,
    marca text DEFAULT 'Generico'::text NOT NULL,
    ubicacion text NOT NULL,
    CONSTRAINT materiales_pkey PRIMARY KEY (id_material)
);

CREATE TABLE public.reactivos_liquidos (
    id_reactivos integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.reactivos_liquidos_id_reactivos_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    num_cas text NOT NULL,
    nombre text NOT NULL,
    formula text NOT NULL,
    marca text DEFAULT 'Generico'::text NOT NULL,
    cantidad integer,
    ubicacion text NOT NULL,
    contenedor text NOT NULL,
    observaciones text,
    CONSTRAINT reactivos_liquidos_pkey PRIMARY KEY (id_reactivos)
);

CREATE TABLE public.reactivos_solidos (
    id_reactivos integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.reactivos_solidos_id_reactivos_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    num_cas text DEFAULT 'NA'::text,
    nombre text NOT NULL,
    formula text DEFAULT 'NA'::text,
    marca text DEFAULT 'Generico'::text NOT NULL,
    cantidad integer,
    ubicacion text NOT NULL,
    contenedor text NOT NULL,
    observaciones text,
    CONSTRAINT reactivos_solidos_pkey PRIMARY KEY (id_reactivos)
);

CREATE TABLE public.sensores (
    id_sensores uuid DEFAULT gen_random_uuid() NOT NULL,
    num_serie text NOT NULL,
    nombre text NOT NULL,
    encargado text,
    ubicacion text NOT NULL,
    "Observaciones" text,
    "Link" text,
    cantidad smallint,
    kit smallint NOT NULL,
    CONSTRAINT sensores_pkey PRIMARY KEY (id_sensores)
);

CREATE TABLE public.ubicacion (
    "Mueble" text NOT NULL,
    "Numero" text DEFAULT 'NA'::text,
    "Estado" text DEFAULT 'NA'::text,
    "Estante" smallint DEFAULT '0'::smallint,
    "Nivel" smallint DEFAULT '0'::smallint,
    id_ubicacion text NOT NULL,
    CONSTRAINT ubicacion_pkey PRIMARY KEY (id_ubicacion)
);

CREATE TABLE public.users (
    id_user SERIAL PRIMARY KEY,                            -- Identificador único
    name VARCHAR(100) NOT NULL,                           -- Nombre del usuario
    email VARCHAR(150) UNIQUE NOT NULL,                  -- Correo electrónico único
    password VARCHAR(255) NOT NULL,                      -- Contraseña (almacenada en forma hasheada)
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,            -- Fecha de creación
    rol VARCHAR(20) CHECK (rol IN ('administrador', 'profesor', 'alumno')) DEFAULT 'alumno', -- Rol del usuario
    active BOOLEAN DEFAULT TRUE                          -- Si el usuario está activo
);

ALTER TABLE ONLY public.kits
    ADD CONSTRAINT public_kits_ubicacion_fkey FOREIGN KEY (ubicacion) REFERENCES public.ubicacion(id_ubicacion) ON UPDATE CASCADE ON DELETE CASCADE;
    
ALTER TABLE ONLY public.manuales
    ADD CONSTRAINT public_manuales_ubicacion_fkey FOREIGN KEY (ubicacion) REFERENCES public.ubicacion(id_ubicacion) ON UPDATE CASCADE ON DELETE CASCADE;
    
ALTER TABLE ONLY public.materiales
    ADD CONSTRAINT public_materiales_ubicacion_fkey FOREIGN KEY (ubicacion) REFERENCES public.ubicacion(id_ubicacion) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.reactivos_liquidos
    ADD CONSTRAINT public_reactivos_liquidos_ubicacion_fkey FOREIGN KEY (ubicacion) REFERENCES public.ubicacion(id_ubicacion) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.reactivos_solidos
    ADD CONSTRAINT public_reactivos_solidos_ubicacion_fkey FOREIGN KEY (ubicacion) REFERENCES public.ubicacion(id_ubicacion) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.sensores
    ADD CONSTRAINT public_sensores_ubicacion_fkey FOREIGN KEY (ubicacion) REFERENCES public.ubicacion(id_ubicacion) ON UPDATE CASCADE ON DELETE CASCADE;

